### ISSUE TITLE
In Announcements, a special article source needs to be added, coming from a remote csv file

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/websites#24]
We need to consider how to implement this.
The current idea is to create a corresponding issue, the content of which contains a link to the csv file.
Then we implement the recognition of the csv link in the issue content and read it and convert it into a markdown table for use.

PRD: https://lb84z6.axshare.com/#g=1&p=help_center

CSV link: https://github.com/nervosnetwork/neuron/blob/develop/compatible.csv

Refs: https://github.com/Magickbase/neuron-public-issues/issues/99

**Comment by WhiteMinds** [comment]
The current solution is to implement a `<!-- PARSE_CSV_TO_MARKDOWN: {url}-->` syntax. When this syntax is detected during parsing, it will automatically read the corresponding CSV file and convert it to a markdown table.

This solution is implemented in https://github.com/Magickbase/neuron-troubleshooting/commit/e9973df36f2d863c814167e48c96cb6aa1382e84.

**Comment by Danie0918** [comment]
![download](https://github.com/Magickbase/neuron-troubleshooting/assets/122437870/f2f9a13a-fe19-4946-a160-081ea80a70ad)

Requirements：Add compatibility table to download page

1. Data source: https://github.com/nervosnetwork/neuron/blob/develop/compatible.csv
2. Neuron versions are sorted from top to bottom, newest to oldest.
3. CKB full node and light client node, according to the width of the page adaptive display , beyond the part need to drag the scroll bar, the part of the blank display.
4. CKB Full and light client nodes are sorted from left to right,newest to oldest.

**Comment by Danie0918** [comment]
UI:https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=19033%3A39943&mode=design&t=QxUiYzkKOOp5Eg1x-1

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/websites/pull/27

**Comment by WhiteMinds** [comment]
Has deployed to the production environment.

https://neuron.magickbase.com/download
